//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPClient.EsendexSoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="com.esendex.ems.soapinterface", ConfigurationName="EsendexSoapService.SendServiceSoap")]
    public interface SendServiceSoap {
        
        // CODEGEN: Generating message contract since message SendMessageRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.SendMessageResponse SendMessage(SOAPClient.EsendexSoapService.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageResponse> SendMessageAsync(SOAPClient.EsendexSoapService.SendMessageRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageFullRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.SendMessageFullResponse SendMessageFull(SOAPClient.EsendexSoapService.SendMessageFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageFull", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageFullResponse> SendMessageFullAsync(SOAPClient.EsendexSoapService.SendMessageFullRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageMultipleRecipientsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipients", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse SendMessageMultipleRecipients(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipients", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse> SendMessageMultipleRecipientsAsync(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageMultipleRecipientsFullRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipientsFull", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse SendMessageMultipleRecipientsFull(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageMultipleRecipientsFull", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse> SendMessageMultipleRecipientsFullAsync(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest request);
        
        // CODEGEN: Generating message contract since message SendMessageBatchRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.SendMessageBatchResponse SendMessageBatch(SOAPClient.EsendexSoapService.SendMessageBatchRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/SendMessageBatch", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageBatchResponse> SendMessageBatchAsync(SOAPClient.EsendexSoapService.SendMessageBatchRequest request);
        
        // CODEGEN: Generating message contract since message GetMessageStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetMessageStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SOAPClient.EsendexSoapService.GetMessageStatusResponse GetMessageStatus(SOAPClient.EsendexSoapService.GetMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="com.esendex.ems.soapinterface/GetMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.GetMessageStatusResponse> GetMessageStatusAsync(SOAPClient.EsendexSoapService.GetMessageStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class MessengerHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usernameField;
        
        private string passwordField;
        
        private string accountField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Account {
            get {
                return this.accountField;
            }
            set {
                this.accountField = value;
                this.RaisePropertyChanged("Account");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public partial class messagesubmission : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string originatorField;
        
        private string recipientField;
        
        private string bodyField;
        
        private MessageContentType typeField;
        
        private int validityperiodField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string originator {
            get {
                return this.originatorField;
            }
            set {
                this.originatorField = value;
                this.RaisePropertyChanged("originator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
                this.RaisePropertyChanged("recipient");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MessageContentType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int validityperiod {
            get {
                return this.validityperiodField;
            }
            set {
                this.validityperiodField = value;
                this.RaisePropertyChanged("validityperiod");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageContentType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        SmartMessage,
        
        /// <remarks/>
        Unicode,
        
        /// <remarks/>
        WapPush,
        
        /// <remarks/>
        LongMessage,
        
        /// <remarks/>
        WDPMessage,
        
        /// <remarks/>
        AdvancedMessage,
        
        /// <remarks/>
        VoiceMessage,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageType {
        
        /// <remarks/>
        Text,
        
        /// <remarks/>
        Binary,
        
        /// <remarks/>
        SmartMessage,
        
        /// <remarks/>
        Unicode,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessage", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public SOAPClient.EsendexSoapService.MessageType type;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type) {
            this.MessengerHeader = MessengerHeader;
            this.recipient = recipient;
            this.body = body;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string SendMessageResult;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(string SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageFull", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageFullRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string originator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string recipient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=3)]
        public SOAPClient.EsendexSoapService.MessageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=4)]
        public int validityperiod;
        
        public SendMessageFullRequest() {
        }
        
        public SendMessageFullRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            this.MessengerHeader = MessengerHeader;
            this.originator = originator;
            this.recipient = recipient;
            this.body = body;
            this.type = type;
            this.validityperiod = validityperiod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageFullResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string SendMessageFullResult;
        
        public SendMessageFullResponse() {
        }
        
        public SendMessageFullResponse(string SendMessageFullResult) {
            this.SendMessageFullResult = SendMessageFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipients", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public SOAPClient.EsendexSoapService.MessageType type;
        
        public SendMessageMultipleRecipientsRequest() {
        }
        
        public SendMessageMultipleRecipientsRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type) {
            this.MessengerHeader = MessengerHeader;
            this.recipients = recipients;
            this.body = body;
            this.type = type;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageMultipleRecipientsResult;
        
        public SendMessageMultipleRecipientsResponse() {
        }
        
        public SendMessageMultipleRecipientsResponse(string[] SendMessageMultipleRecipientsResult) {
            this.SendMessageMultipleRecipientsResult = SendMessageMultipleRecipientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsFull", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsFullRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string originator;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=1)]
        public string[] recipients;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=2)]
        public string body;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=3)]
        public SOAPClient.EsendexSoapService.MessageType type;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=4)]
        public int validityperiod;
        
        public SendMessageMultipleRecipientsFullRequest() {
        }
        
        public SendMessageMultipleRecipientsFullRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            this.MessengerHeader = MessengerHeader;
            this.originator = originator;
            this.recipients = recipients;
            this.body = body;
            this.type = type;
            this.validityperiod = validityperiod;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageMultipleRecipientsFullResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageMultipleRecipientsFullResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageMultipleRecipientsFullResult;
        
        public SendMessageMultipleRecipientsFullResponse() {
        }
        
        public SendMessageMultipleRecipientsFullResponse(string[] SendMessageMultipleRecipientsFullResult) {
            this.SendMessageMultipleRecipientsFullResult = SendMessageMultipleRecipientsFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageBatch", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageBatchRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public SOAPClient.EsendexSoapService.messagesubmission[] messages;
        
        public SendMessageBatchRequest() {
        }
        
        public SendMessageBatchRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, SOAPClient.EsendexSoapService.messagesubmission[] messages) {
            this.MessengerHeader = MessengerHeader;
            this.messages = messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SendMessageBatchResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class SendMessageBatchResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string[] SendMessageBatchResult;
        
        public SendMessageBatchResponse() {
        }
        
        public SendMessageBatchResponse(string[] SendMessageBatchResult) {
            this.SendMessageBatchResult = SendMessageBatchResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="com.esendex.ems.soapinterface")]
    public enum MessageStatusCode {
        
        /// <remarks/>
        Queued,
        
        /// <remarks/>
        Sent,
        
        /// <remarks/>
        Delivered,
        
        /// <remarks/>
        Failed,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageStatus", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="com.esendex.ems.soapinterface")]
        public SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public string id;
        
        public GetMessageStatusRequest() {
        }
        
        public GetMessageStatusRequest(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string id) {
            this.MessengerHeader = MessengerHeader;
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetMessageStatusResponse", WrapperNamespace="com.esendex.ems.soapinterface", IsWrapped=true)]
    public partial class GetMessageStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="com.esendex.ems.soapinterface", Order=0)]
        public SOAPClient.EsendexSoapService.MessageStatusCode GetMessageStatusResult;
        
        public GetMessageStatusResponse() {
        }
        
        public GetMessageStatusResponse(SOAPClient.EsendexSoapService.MessageStatusCode GetMessageStatusResult) {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SendServiceSoapChannel : SOAPClient.EsendexSoapService.SendServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SendServiceSoapClient : System.ServiceModel.ClientBase<SOAPClient.EsendexSoapService.SendServiceSoap>, SOAPClient.EsendexSoapService.SendServiceSoap {
        
        public SendServiceSoapClient() {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SendServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.SendMessageResponse SOAPClient.EsendexSoapService.SendServiceSoap.SendMessage(SOAPClient.EsendexSoapService.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public string SendMessage(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type) {
            SOAPClient.EsendexSoapService.SendMessageRequest inValue = new SOAPClient.EsendexSoapService.SendMessageRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            SOAPClient.EsendexSoapService.SendMessageResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessage(inValue);
            return retVal.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageResponse> SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageAsync(SOAPClient.EsendexSoapService.SendMessageRequest request) {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageResponse> SendMessageAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type) {
            SOAPClient.EsendexSoapService.SendMessageRequest inValue = new SOAPClient.EsendexSoapService.SendMessageRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.SendMessageFullResponse SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageFull(SOAPClient.EsendexSoapService.SendMessageFullRequest request) {
            return base.Channel.SendMessageFull(request);
        }
        
        public string SendMessageFull(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            SOAPClient.EsendexSoapService.SendMessageFullRequest inValue = new SOAPClient.EsendexSoapService.SendMessageFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            SOAPClient.EsendexSoapService.SendMessageFullResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageFull(inValue);
            return retVal.SendMessageFullResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageFullResponse> SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageFullAsync(SOAPClient.EsendexSoapService.SendMessageFullRequest request) {
            return base.Channel.SendMessageFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageFullResponse> SendMessageFullAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string recipient, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            SOAPClient.EsendexSoapService.SendMessageFullRequest inValue = new SOAPClient.EsendexSoapService.SendMessageFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipient = recipient;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageMultipleRecipients(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest request) {
            return base.Channel.SendMessageMultipleRecipients(request);
        }
        
        public string[] SendMessageMultipleRecipients(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type) {
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest inValue = new SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageMultipleRecipients(inValue);
            return retVal.SendMessageMultipleRecipientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse> SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageMultipleRecipientsAsync(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest request) {
            return base.Channel.SendMessageMultipleRecipientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsResponse> SendMessageMultipleRecipientsAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type) {
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest inValue = new SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageMultipleRecipientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageMultipleRecipientsFull(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest request) {
            return base.Channel.SendMessageMultipleRecipientsFull(request);
        }
        
        public string[] SendMessageMultipleRecipientsFull(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest inValue = new SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageMultipleRecipientsFull(inValue);
            return retVal.SendMessageMultipleRecipientsFullResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse> SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageMultipleRecipientsFullAsync(SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest request) {
            return base.Channel.SendMessageMultipleRecipientsFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullResponse> SendMessageMultipleRecipientsFullAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string originator, string[] recipients, string body, SOAPClient.EsendexSoapService.MessageType type, int validityperiod) {
            SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest inValue = new SOAPClient.EsendexSoapService.SendMessageMultipleRecipientsFullRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.originator = originator;
            inValue.recipients = recipients;
            inValue.body = body;
            inValue.type = type;
            inValue.validityperiod = validityperiod;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageMultipleRecipientsFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.SendMessageBatchResponse SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageBatch(SOAPClient.EsendexSoapService.SendMessageBatchRequest request) {
            return base.Channel.SendMessageBatch(request);
        }
        
        public string[] SendMessageBatch(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, SOAPClient.EsendexSoapService.messagesubmission[] messages) {
            SOAPClient.EsendexSoapService.SendMessageBatchRequest inValue = new SOAPClient.EsendexSoapService.SendMessageBatchRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.messages = messages;
            SOAPClient.EsendexSoapService.SendMessageBatchResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageBatch(inValue);
            return retVal.SendMessageBatchResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageBatchResponse> SOAPClient.EsendexSoapService.SendServiceSoap.SendMessageBatchAsync(SOAPClient.EsendexSoapService.SendMessageBatchRequest request) {
            return base.Channel.SendMessageBatchAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.SendMessageBatchResponse> SendMessageBatchAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, SOAPClient.EsendexSoapService.messagesubmission[] messages) {
            SOAPClient.EsendexSoapService.SendMessageBatchRequest inValue = new SOAPClient.EsendexSoapService.SendMessageBatchRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.messages = messages;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).SendMessageBatchAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPClient.EsendexSoapService.GetMessageStatusResponse SOAPClient.EsendexSoapService.SendServiceSoap.GetMessageStatus(SOAPClient.EsendexSoapService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatus(request);
        }
        
        public SOAPClient.EsendexSoapService.MessageStatusCode GetMessageStatus(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string id) {
            SOAPClient.EsendexSoapService.GetMessageStatusRequest inValue = new SOAPClient.EsendexSoapService.GetMessageStatusRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.id = id;
            SOAPClient.EsendexSoapService.GetMessageStatusResponse retVal = ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).GetMessageStatus(inValue);
            return retVal.GetMessageStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.GetMessageStatusResponse> SOAPClient.EsendexSoapService.SendServiceSoap.GetMessageStatusAsync(SOAPClient.EsendexSoapService.GetMessageStatusRequest request) {
            return base.Channel.GetMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPClient.EsendexSoapService.GetMessageStatusResponse> GetMessageStatusAsync(SOAPClient.EsendexSoapService.MessengerHeader MessengerHeader, string id) {
            SOAPClient.EsendexSoapService.GetMessageStatusRequest inValue = new SOAPClient.EsendexSoapService.GetMessageStatusRequest();
            inValue.MessengerHeader = MessengerHeader;
            inValue.id = id;
            return ((SOAPClient.EsendexSoapService.SendServiceSoap)(this)).GetMessageStatusAsync(inValue);
        }
    }
}
